### ISSUE TITLE
Compatibility with Julia 0.4

### ISSUE THREAD

**Issue by waldyrious** [JuliaMath/Tau.jl#13]
Currently testing in 0.4 fails: https://github.com/waldyrious/Tau.jl/pull/1

To fix this, [Compat](https://github.com/JuliaLang/Compat.jl) macros will almost certainly be needed.

See #12 for context.

**Comment by giordano** [comment]
Is support for Julia 0.4 still wanted?  If not, the two `@vectorize_1arg` call can be removed.

**Comment by waldyrious** [comment]
I would personally like to try it, as a personal exercise (I haven't used Compat.jl yet) but I wouldn't want to compromise the code's readability or simplicity too much for that.

Considering that 0.6-rc1 has been tagged, I suppose it makes sense to start considering Julia's past, current, and next releases to be 0.5, 0.6 and 0.7, respectively. So if you think it makes sense to do this, feel free to go ahead -- no objections on my part.

**Comment by giordano** [comment]
Personally I'd go ahead, the package will continue to work on Julia 0.4 anyway and if necessary bug fixes can be backported.  There won't be new features for that version of Julia, but I don't think this simple package is going to receive a great load of new functions.

Anyway, from what I can see, the only test that doesn't pass on Julia 0.4 is the first one, `@test_broken tau == 2*pi`.  Just drop `_broken`?

**Comment by waldyrious** [comment]
> Anyway, from what I can see, the only test that doesn't pass on Julia 0.4 is the first one, `@test_broken tau == 2*pi`. Just change it?

Is that all? Wow, I'm embarrassed to have missed that. I suppose we could just wrap that test with an `if VERSION < v"0.5-"` check, and do `@test tau ≠ 2*pi` in the else block, right?

**Comment by giordano** [comment]
> Is that all?

Actually no.  I just discovered an inconsistent behavior between Julia 0.4 and 0.5 in complex sin/cos.  Will submit a PR in a few minutes.

Anyway, I would always test `tau ≠ 2*pi`  The fact that `tau` is not equal to `2*pi` makes this package useful, otherwise would be redundant.

**Comment by waldyrious** [comment]
Ok, let's close this when 0.6 is officially released. The badges in the readme will need to be updated then.
