### ISSUE TITLE
Tests failing in julia nightly

### ISSUE THREAD

**Issue by waldyrious** [JuliaMath/Tau.jl#26]
See for example https://travis-ci.org/JuliaMath/Tau.jl/jobs/245339601 (from #25):

```
INFO: Testing Tau
Error During Test
  Test threw an exception of type ErrorException
  Expression: #= /home/travis/.julia/v0.7/Tau/test/runtests.jl:39 =# @inferred(sintau(T(x))) == sign(x) * zero(T)
  return type BigFloat does not match inferred return type Any
  Stacktrace:
   [1] macro expansion at /home/travis/.julia/v0.7/Tau/test/runtests.jl:39 [inlined]
   [2] anonymous at ./<missing>:?
   [3] include_from_node1(::Module, ::String) at ./loading.jl:549
   [4] include(::Module, ::String) at ./sysimg.jl:14
   [5] process_options(::Base.JLOptions) at ./client.jl:310
   [6] _start() at ./client.jl:378
ERROR: LoadError: There was an error during testing
while loading /home/travis/.julia/v0.7/Tau/test/runtests.jl, in expression starting on line 38
```

**Comment by giordano** [comment]
The problem is with `T = BigFloat`, but I can't understand why inference fails here.

Anyway, as I said in PR #19, `sintau` and `costau` can be improved by adapting them to new definitions of `sinpi` and `cospi`, which are more efficient.

**Comment by waldyrious** [comment]
Do you have plans to work on those anytime soon? Tau day is coming up (a week from now), and I'd like to make a release for the occasion -- it would be nice if we could include this fix in it. What are the main hurdles to adjust `sintau` and `costau` to match the new implementations of `sinpi`/`cospi` from Base, in your view?

**Comment by giordano** [comment]
No, I don't plan to work on this, mostly because internals of `sinpi` and `cospi` are obscure to me, so I wouldn't know how to adapt to this case :)

**Comment by waldyrious** [comment]
Yeah, they look pretty opaque to me too. I'll probably spend some time "decoding" them once I get the time.

That said, do you think there's a way we could adjust the current code to avoid this failure? We can add a separate issue to track the re-syncing of those methods' code with the corresponding versions in Base.

**Comment by giordano** [comment]
To avoid the failure we can just remove the `@inferred`, but the test will fail also at https://github.com/JuliaMath/Tau.jl/blob/a9142e342e17b41ef173fbc7e208cb35aa876d25/test/runtests.jl#L97 when `T = BigFloat`.

Maybe try asking on [discourse](http://discourse.julialang.org/) if someone has a clue about why `sintau` is unstable with `T = BigFloat` input?

**Comment by giordano** [comment]
I think this is no more an issue:
```julia
julia> using Tau, Test

julia> @inferred sintau(big(6.28))
0.9822872507286883882901415948346156477307161222321188530528350428954190590918724
```
@waldyrious could you please confirm?

**Comment by devmotion** [comment]
Works for me as well.
