### ISSUE TITLE
Package compatibility caps

### ISSUE THREAD

**Issue by KZiemian** [JuliaMath/Tau.jl#34]
Ref: https://discourse.julialang.org/t/package-compatibility-caps/15301

**Comment by BioTurboNick** [comment]
+1, please update

**Comment by waldyrious** [comment]
If anyone could submit a PR, it would be greatly appreciated and swiftly merged.

**Comment by giordano** [comment]
I don't think you need to do anything beside tagging a new version

**Comment by giordano** [comment]
You can actually also uncap the package in this way in METADATA.jl: https://github.com/JuliaLang/METADATA.jl/pull/18210/files but since there have been changes since last tagged version, rolling a new release makes sense anyway

**Comment by BioTurboNick** [comment]
It might need a Project.toml. I could try to do that.

**Comment by giordano** [comment]
No, it doesn't

**Comment by waldyrious** [comment]
@giordano since you clearly know more about this process than I do, would you like to do the honors? :)

**Comment by giordano** [comment]
Done! https://github.com/JuliaLang/METADATA.jl/pull/21089
